// File generated by CONVERT_PALETTE macro from CPCtelera
// Converted firmware palette declaration
// 
#ifndef __pal_main_H_
#define __pal_main_H_

#include <types.h>

extern const u8 _pal_main[16];

#endif
