// File generated by CONVERT_PALETTE macro from CPCtelera
// Converted firmware palette declaration
// 
#ifndef _pal_main_H_
#define _pal_main_H_

#include <types.h>

extern const u8 pal_main[16];

#endif
